# Generated by Django 4.1.2 on 2022-10-28 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_brand', models.CharField(max_length=5)),
                ('mb', models.IntegerField(null=True)),
                ('cpu', models.IntegerField(null=True)),
                ('gpu', models.IntegerField(null=True)),
                ('ram', models.IntegerField(null=True)),
                ('rf', models.IntegerField(null=True)),
                ('cs', models.IntegerField(null=True)),
                ('ps', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.component')),
                ('fan_slots', models.IntegerField()),
            ],
            bases=('builder.component',),
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.component')),
                ('socket', models.CharField(choices=[('None', 'None'), ('AMD', 'AMD'), ('Intel', 'Intel')], max_length=5)),
            ],
            bases=('builder.component',),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.component')),
                ('vram', models.IntegerField()),
            ],
            bases=('builder.component',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.component')),
                ('socket', models.CharField(choices=[('None', 'None'), ('AMD', 'AMD'), ('Intel', 'Intel')], max_length=5)),
                ('ram_slots', models.IntegerField(default=0)),
            ],
            bases=('builder.component',),
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.component')),
                ('potency', models.IntegerField()),
            ],
            bases=('builder.component',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.component')),
                ('capacity', models.IntegerField()),
            ],
            bases=('builder.component',),
        ),
        migrations.CreateModel(
            name='RefSystem',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.component')),
                ('coverage', models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('FULL', 'FULL')], max_length=4)),
            ],
            bases=('builder.component',),
        ),
    ]
