# Generated by Django 4.1.1 on 2022-10-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ram',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
