# Generated by Django 4.1.2 on 2022-10-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_brand', models.CharField(max_length=5)),
                ('mb', models.IntegerField(default=None)),
                ('cpu', models.IntegerField(default=None)),
                ('gpu', models.IntegerField(default=None)),
                ('ram', models.IntegerField(default=None)),
                ('rf', models.IntegerField(default=None)),
                ('cs', models.IntegerField(default=None)),
                ('ps', models.IntegerField(default=None)),
            ],
        ),
    ]
