# Generated by Django 4.1.2 on 2022-10-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cpu_brand',
            field=models.CharField(choices=[('AMD', 'AMD'), ('Intel', 'Intel')], max_length=5),
        ),
    ]
