# Generated by Django 4.1.1 on 2022-10-31 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_remove_refsystem_coverage_refsystem_number_fans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefSystem',
        ),
    ]
