# Generated by Django 4.1.2 on 2022-10-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_alter_order_cpu_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='cs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='gpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='mb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='ps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='ram',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='rf',
            field=models.IntegerField(default=0),
        ),
    ]
