# Generated by Django 4.1.2 on 2022-10-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_order_cpu_alter_order_cs_alter_order_gpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cpu_brand',
            field=models.CharField(max_length=5),
        ),
    ]
