# Generated by Django 4.1.1 on 2022-10-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_delete_refsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefSystem',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='builder.component')),
                ('number_fans', models.IntegerField()),
            ],
            bases=('builder.component',),
        ),
    ]
