# Generated by Django 4.1.1 on 2022-10-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_refsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='consumption',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
