# Generated by Django 4.1.2 on 2022-10-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_alter_order_cpu_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='socket',
            field=models.CharField(choices=[('AMD', 'AMD'), ('Intel', 'Intel')], default='None', max_length=5),
            preserve_default=False,
        ),
    ]
