# Generated by Django 4.1.2 on 2022-11-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_component_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=models.CharField(choices=[('None', 'None'), ('amd', 'AMD'), ('intel', 'Intel')], max_length=5),
        ),
    ]
