# Generated by Django 4.1.2 on 2022-11-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_rename_cs_order_case_rename_mb_order_motherboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='c_type',
            field=models.CharField(choices=[('cpu', 'CPU'), ('motherboard', 'Mother'), ('gpu', 'GPU'), ('ram', 'RAM'), ('ref_system', 'Ref. System'), ('case', 'Case'), ('power_supply', 'Power Supply')], default='cpu', max_length=12),
            preserve_default=False,
        ),
    ]
